name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - production # Change this to the branch you want to deploy from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install # Install dependencies

      - name: Build Project
        run: npm run build # Run build only

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.2.1
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
