name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main # Use the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install # Ensures vite and other packages are installed

      - name: Build Project
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TERRABLOOM_8DC91 }}
          channelId: live
          projectId: terrabloom-8dc91
